### ISSUE TITLE
Center Image button not working

### ISSUE THREAD

**Issue by Benny739** [xeger/quill-image#1]
Thanks for the package, it's the only quill image package that seems to properly work.
The only thing I couldn't get working was the center image button. I also tried to fix it myself, but couldn't find why the float style is not removed.

**Comment by xeger** [comment]
I'm sorry for the long delay @Benny739; I completely missed this when you opened it.

I've published v0.5.2 which should fix the issue you describe, plus add some various other niceties. The API has changed ever so slightly, so please skim the README and adjust accordingly.
