### ISSUE TITLE
Style width/height don't work properly

### ISSUE THREAD

**Issue by morecpq** [xeger/quill-image#13]
I would expect style="width:20px; height:20px;" to translate to width="20px" height="20px" but that isn't happening.

Made a slight modification to your example page.
`<!DOCTYPE html>

<html>

<head>
  <link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">
  <script src="https://cdn.quilljs.com/1.3.7/quill.js"></script>
</head>

<body>
  <div id="editor" style="overflow: hidden;">
    <img src="https://raw.githubusercontent.com/xeger/quill-image/main/assets/256x256.png" style="float: left; width:200px; height:100px;" />
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
    aliqua. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Et tortor at risus viverra adipiscing at in
    tellus integer. Lectus urna duis convallis convallis tellus id interdum. Pellentesque elit eget gravida cum.
    Dignissim suspendisse in est ante in. Eu facilisis sed odio morbi quis commodo odio aenean sed. Ipsum nunc aliquet
    bibendum enim facilisis gravida. Nulla malesuada pellentesque elit eget. Varius duis at consectetur lorem donec
    massa sapien faucibus. Integer malesuada nunc vel risus commodo. Et egestas quis ipsum suspendisse ultrices gravida
    dictum fusce. Risus commodo viverra maecenas accumsan lacus vel. Volutpat sed cras ornare arcu dui vivamus arcu
    felis bibendum.
  </div>
  <script type="module">
    import { ImageActions } from 'https://cdn.jsdelivr.net/npm/@xeger/quill-image-actions/lib/index.js';
    import { ImageFormats } from 'https://cdn.jsdelivr.net/npm/@xeger/quill-image-formats/lib/index.js';

    Quill.register('modules/imageActions', ImageActions);
    Quill.register('modules/imageFormats', ImageFormats);

    const quill = new Quill('#editor', {
      formats: ['align', 'background', 'blockquote', 'bold', 'code-block', 'color', 'float', 'font', 'header', 'height', 'image', 'italic', 'link', 'script', 'strike', 'size', 'underline', 'width'],
      modules: {
        imageActions: {},
        imageFormats: {},
        toolbar: [
          ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
          ['blockquote', 'code-block'],

          [{ 'header': 1 }, { 'header': 2 }],               // custom button values
          [{ 'list': 'ordered' }, { 'list': 'bullet' }],
          [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
          [{ 'indent': '-1' }, { 'indent': '+1' }],          // outdent/indent
          [{ 'direction': 'rtl' }],                         // text direction

          [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
          [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

          [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
          [{ 'font': [] }],
          [{ 'align': [] }],

          ['clean']
        ]
      },
      theme: 'snow'
    });
    
    console.log(document.getElementsByClassName('ql-editor')[0].innerHTML.replace('<div class="ql-clipboard" contenteditable="true" tabindex="-1"></div>', ''));

    quill.on('text-change',
      () => console.log(document.getElementsByClassName('ql-editor')[0].innerHTML.replace('<div class="ql-clipboard" contenteditable="true" tabindex="-1"></div>', ''))
    );
  </script>
</body>

</html>`

Here's the output.
`<p><img src="https://raw.githubusercontent.com/xeger/quill-image/main/assets/256x256.png" style="float: left;"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Et tortor at risus viverra adipiscing at in tellus integer. Lectus urna duis convallis convallis tellus id interdum. Pellentesque elit eget gravida cum. Dignissim suspendisse in est ante in. Eu facilisis sed odio morbi quis commodo odio aenean sed. Ipsum nunc aliquet bibendum enim facilisis gravida. Nulla malesuada pellentesque elit eget. Varius duis at consectetur lorem donec massa sapien faucibus. Integer malesuada nunc vel risus commodo. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Risus commodo viverra maecenas accumsan lacus vel. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum.</p>`

The width/height get completely stripped.

**Comment by xeger** [comment]
This is somewhat by design. Rather than trying to parse styles and deal with CSS units, `quill-image-formats` uses the `width` and `height` _attributes_ of the `img` tag -- not the `style` attribute -- to control image dimensions. See it here:
https://github.com/xeger/quill-image/blob/main/packages/quill-image-formats/src/formats.ts#L14

I don't object to using styles; I just didn't want to deal with the complexity since it isn't needed for any of my use cases.

Are `width` and `height` attributes acceptable to you? If they're not, then is it acceptable if we "down-convert" CSS dimensions to `width` and `height` on paste, or do you need to preserve CSS dimensions in the HTML output of the editor too?

**Comment by morecpq** [comment]
The “down convert” is what I’m looking for. 👍🏻 🙂  it makes most sense since that’s what the default editor uses when resizing images and it’s an easy convert since it’s exact ***@***.*** Sep 2, 2022, at 7:21 PM, Tony Spataro ***@***.***> wrote:﻿
This is somewhat by design. Rather than trying to parse styles and deal with CSS units, quill-image-formats uses the width and height attributes of the img tag -- not the style attribute -- to control image dimensions. See it here:
https://github.com/xeger/quill-image/blob/main/packages/quill-image-formats/src/formats.ts#L14
I don't object to using styles; I just didn't want to deal with the complexity since it isn't needed for any of my use cases.
Are width and height attributes acceptable to you? If they're not, then is it acceptable if we "down-convert" CSS dimensions to width and height on paste, or do you need to preserve CSS dimensions in the HTML output of the editor too?

**Comment by xeger** [comment]
Okay; thank you for the feedback. Down convert should be relatively easy; I'll give it a try tonight.

**Comment by morecpq** [comment]
Thank you so ***@***.*** Sep 27, 2022, at 7:52 PM, Tony Spataro ***@***.***> wrote:﻿
Okay; thank you for the feedback. Down convert should be relatively easy; I'll give it a try tonight.

**Comment by xeger** [comment]
Here's [downconvert](https://github.com/xeger/quill-image/pull/16) for pixel-unit CSS only. If you know how to do easy unit conversion (em, in, cm, etc) LMK and I will add that too.

Will release a patchlevel as soon as the build goes green.

**Comment by xeger** [comment]
See [v0.7.1](https://github.com/xeger/quill-image/releases/tag/v0.7.1) @morecpq
