### ISSUE TITLE
FF - execCommand not needed

### ISSUE THREAD

**Issue by johanneswilm** [xeger/quill-image#23]
Hey,
Firefox stopped requiring disabling controls five years ago [1]. So you are now able to remove your last usages of `document.execCommand` for things like "enableInlineTableEditing" or "enableObjectResizing".

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1490641

**Comment by xeger** [comment]
Thank you for the information @johanneswilm; I have released v0.7.2 with your recommended change.
