### ISSUE TITLE
How to preserve the original style attribute of image?

### ISSUE THREAD

**Issue by luokelong** [xeger/quill-image#25]
While using quill.setContents(quill.clipboard.convert(value)) to set editor conent, the module will remove its style attribute.

Some html string like:
```
<p><img src="..." style="display:block;margin:0 auto;" /></p>
```

After setContents it will to be:
```
<p><img src="..." /></p>
```

But I hope it can preserve the style attribute and show its real align.

How to impl this feature?

**Comment by xeger** [comment]
Quill cannot preserve arbitrary HTML attributes. That isn't how it works. The HTML you see in the editor is a rendering, or a view, of the actual rich-text data which is represented as a `Delta`. The HTML is destroyed and re-created whenever the data changes.

If you want to edit raw HTML, you should use an editor other than Quill.
